apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}-configmap
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 5060;
        server_name wildrootskitchenandbar.co.uk www.wildrootskitchenandbar.co.uk;
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        location / {
          root /usr/share/nginx/html;
          index index.html;
          access_log off;
          try_files $uri $uri/ /index.html;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
          root /usr/share/nginx/html;
          internal;
        }
      }
    }