apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}-configmap
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
data:
  # Configuration for Apache + PHP setup
  # Apache will handle PHP processing automatically with mod_php
  app.conf: |
    # Application configuration
    ServerName {{ .Values.webserver.host }}
    DocumentRoot /var/www/html