apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.webserver.applicationType }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.webserver.applicationType }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}-deployment
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webserver.applicationType }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/instance: wildroots-frontend
    spec:
      containers:
      - name: {{ .Values.webserver.applicationType }}
        image: {{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "96Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "250m"

        # No volume mounts needed for Apache + PHP setup  